# Generated by Django 5.0.2 on 2024-02-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuerpo',
            field=models.TextField(help_text='Incluye el contenido de tu articulo'),
        ),
    ]
